server: 
  port: 9005
spring: 
  application:  
    name: tensquare-spit #指定服务名
  data:
    mongodb:
      username: spit
      password: 123456
      uri: mongodb://106.15.233.201:27020/spitdb
  redis:
    client-name: ${spring.application.name}
    sentinel:
      nodes:
        - 106.15.233.201:26379
        - 106.15.233.201:26380
        - 106.15.233.201:26381
      master: mymaster

