server: 
  port: 9005
spring: 
  application:  
    name: tensquare-spit #指定服务名
  data:
    mongodb:
      username: wp
      password: 123456
      uri: mongodb://wp:123456@106.15.233.201:27020/spitdb
  redis:
    client-name: ${spring.application.name}
    sentinel:
      nodes:
        - 106.15.233.201:26379
        - 106.15.233.201:26380
        - 106.15.233.201:26381
      master: mymaster
eureka:
  instance:
    instance-id: ${spring.application.name}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:9000/eureka/
