server: 
  port: 9004
spring: 
  application:  
    name: tensquare_article #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.15.233.201:3306/tensquare_article?characterEncoding=UTF8
    username: root
    password: 123456
  jpa: 
    database: MySQL
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9000/eureka/
  instance:
    instance-id: ${spring.application.name}
    prefer-ip-address: true
