server: 
  port: 9005
spring: 
  application:  
    name: tensquare_gathering #指定服务名
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.15.233.201:3306/tensquare_gathering?characterEncoding=UTF8
    username: root
    password: 123456
  jpa: 
    database: MySQL
    show-sql: true
  redis:
    client-name: ${spring.application.name}
    sentinel:
      nodes:
        - 106.15.233.201:26379
        - 106.15.233.201:26380
        - 106.15.233.201:26381
      master: mymaster
eureka:
  instance:
    instance-id: ${spring.application.name}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:9000/eureka/
feign:
  hystrix:
    enabled: false
  sentinel:
    enabled: true
  httpclient:
    enabled: true
  client:
    config:
      tensquare-base:
        connectTimeout: 2000
        readTimeout: 3000
#tensquare-base:
  #ribbon:
    #配置单个节点重试最大值
    #MaxAutoRetries: 1
    #配置更换节点数最大值
    #MaxAutoRetriesNextServer: 1
#hystrix:
  #command:
    #defalut:
      #execution:
        #isolation:
          #thread:
            #timeoutInMilliseconds: 2000

