server: 
  port: 9005
spring: 
  application:  
    name: tensquare_gathering #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.15.233.201:3306/tensquare_gathering?characterEncoding=UTF8
    username: root
    password: 123456
  jpa: 
    database: MySQL
    show-sql: true
  redis:
    client-name: ${spring.application.name}
    sentinel:
      nodes:
        - 106.15.233.201:26379
        - 106.15.233.201:26380
        - 106.15.233.201:26381
      master: mymaster
